[tool.black]
line-length = 100
target_version = ['py39']
include = '\.pyi?$'
exclude = '''
(
  /(
    | \.git
    | \.mypy_cache
    | __pycache__
    | generated
  )/
)
'''

[tool.isort]
profile = "black"
